name: tests

on:
  push:
    branches:
      - "**"
      - "!main"
  pull_request:
    branches:
      - "**"
      - "!main"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REACT_APP_RECAPTCHA_SITE_KEY: ${{ secrets.REACT_APP_RECAPTCHA_SITE_KEY }}
      REACT_APP_API: ${{ secrets.REACT_APP_API }}
      REACT_APP_DOMAIN_NAME: ${{ secrets.REACT_APP_DOMAIN_NAME }}

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          # cache: "npm"

      - name: Install dependencies
        run: yarn install

      - name: Set react env variables
        run: |
          echo REACT_APP_RECAPTCHA_SITE_KEY="${{ env.REACT_APP_RECAPTCHA_SITE_KEY }}" >> .env
          echo REACT_APP_API="${{ env.REACT_APP_API }}" >> .env
          echo REACT_APP_DOMAIN_NAME="${{ env.REACT_APP_DOMAIN_NAME }}" >> .env

      - name: Run tests
        run: yarn test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

      - name: Build
        run: CI=false yarn build
